<!DOCTYPE html>
<html class="no-js" lang="en" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="The Life and Death of a Political Startup" />
  <meta property="og:site_name" content="Poliana" />
  <meta property="og:url" content="http://www.poliana.com" />
  <meta property="og:description" content="Poliana ran out of money and we’re really sad to say we have to shut down the project. We gave this our all and have decided in good faith to open source everything for use by others for whatever purpose you so desire. Hopefully our code and designs will live on to other really awesome projects. For the time being, we need to focus on exploring other opportunities before someday maybe getting back to the project (besides, it’s not exactly the kind of project that makes you a millionaire, or even pays rent)." />
  <meta property="og:image" content="http://www.poliana.com/images/logo-facebook.png" />

  <title>The Life and Death of a Political Startup</title>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:300italic,300,700,700italic|Cabin:600italic,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/styles.css">

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58661735-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>
  <div id="content">
    <img src="images/logo.png" id="logo" alt="Poliana" class="wow fadeIn">
    <h2 class="center wow fadeIn">The Life and Death of a Political Startup</h2>
    <p class="wow fadeIn">Poliana ran out of money and we’re really sad to say we have to shut down the project. We gave this our all and have decided in good faith to open source everything for use by others for whatever purpose you so desire. Hopefully our code and designs will live on to other really awesome projects. For the time being, we need to focus on exploring other opportunities before someday maybe getting back to the project (besides, it’s not exactly the kind of project that makes you a millionaire, or even pays rent). There are a lot of great lessons we learned described below, but we also wrote this paragraph for the lazier of Hacker News patrons. If you want to get in contact with us for whatever reason (death threats are certainly preferable, we like those), then please <a href="mailto:polianaproject@gmail.com">drop us a line</a>.</p>
    <hr class="wow fadeIn">
    <p class="wow fadeIn">Dear Internet,</p>
    <p class="wow fadeIn">Our journey began a long time ago in a galaxy far, far away... but for all intents and purposes let’s just say it began in May 2013. Last week, however, we decided it’s best to close our doors, leave our homes, and hitchhike out of town. This is the best decision for us at the moment for a number of reasons we’ll get into shortly, but for now allow us to be slightly sentimental.</p>
    <h3 class="wow fadeIn">A Brief History of Time</h3>
    <p class="wow fadeIn">Roughly a year and a half ago we began with the desire to help bring a pinch of order to the chaos that is the United States political system. It was, and has always been, somewhat of a naïve (or “Pollyanna”-ish if you’re into puns) way of thinking. Our team started with four fine gentlemen: cousins Seth and Shawn Whiting, Kenny House, and Grayson Carroll. This team joined a for-profit business incubator in Nashville, the <a href="http://jsf.co" target="_blank">Jumpstart Foundry</a>, and went through a four-month program of zero-to-hero training in entrepreneurship, management, raising money (or not), and general business badassery.</p>
    <p class="wow fadeIn">Originally the idea of Poliana (a <a href="http://en.wikipedia.org/wiki/Portmanteau" target="_blank">portmanteau</a> of “political analytics”, and also a double entendre) was to provide a gateway for politicians and their constituents to better communicate. When we looked at the political system originally we saw an unorganized mess (called government) failing to address the concerns of an uninformed mess (called constituents). Because 24-hour news outlets are run by humans, biased and opinionated creatures, their viewers often trust none of what they say or they believe only what one media organization says. Both outcomes are massive problems and both lead to rampant misinformation, misguided opinions, and angry Facebook posts that get brought up by your relatives during Thanksgiving dinner.</p>
    <p class="wow fadeIn">Likewise we had grown pretty aware over how insignificant people actually are in influencing their government. Princeton <a href="http://scholar.princeton.edu/sites/default/files/mgilens/files/gilens_and_page_2014_-testing_theories_of_american_politics.doc.pdf" target="blank">released a terrifying study</a> last September that basically says that the general public’s opinion doesn’t matter. To quote the study’s summary: “Multivariate analysis indicates that economic elites and organized groups representing business interests have substantial independent impacts on U.S. government policy, while <em>average citizens and mass-based interest groups have little or no independent influence.</em>” In a nutshell: suck it Occupy Wall Street.</p>
    <p class="wow fadeIn">It all goes back to the whole assumption of our idea was that there was a failure in communication between the government and its citizens that we inferred was from outdated or nonexistent technology. However, as we began the vetting process of our idea by interviewing citizens and politicians alike, we determined three very important bits of insight:</p>
    <ol class="wow fadeIn" start="0">
      <li>Politicians generally don’t care about what their constituents think.</li>
      <li>Constituents generally don’t care about, much less like, their politicians.</li>
      <li>Because constituents have grown tired of the caricature of the American political system, they have since become apathetic towards it.</li>
    </ol>
    <p class="wow fadeIn">Naturally there are outliers on both sides, but we soon learned the issue had little to do with communication and a whole lot to do with education. About a month into the program, the team sought the help of two other developers: Patrick Cason (myself) and David Gilmore (not from <a href="http://en.wikipedia.org/wiki/David_Gilmour" target="_blank">Pink Floyd</a>). It was determined by this now team of six fine gentlemen that we required a massive pivot in concept.</p>
    <h3 class="wow fadeIn">The Pivot</h3>
    <p class="wow fadeIn">This pivot entailed becoming a big data company, focused on enlightening the American people on their government via easy to understand data visualizations. The goal of such a site would be to educate Americans on the political system so that they might hopefully care more about the politicians they elect into office and less about the parties with which they are associated. Our guiding philosophy was that since traditional media outlets are run by (biased) human beings, what was needed is a site driven entirely by data. We worked tirelessly to gain the support of political-based entities like the <a href="http://sunlightfoundation.com/" target="_blank">Sunlight Foundation</a>, <a href="https://www.opensecrets.org/" target="_blank">Center for Responsive Politics</a>, <a href="http://www.loc.gov/" target="_blank">Library of Congress</a>, and <a href="https://www.govtrack.us/" target="_blank">Govtrack</a>. We will praise these awesome groups for their datasets, support, and general wizardry later (but let’s be honest... we all about dat data [no treble!]).</p>
    <p class="wow fadeIn">After all was said and done, our database stood tall at well over 100 million rows of data on campaign finance, lobbyist donations, politician metadata, and records of every vote of every bill in the last 30 years of the Senate and House of Representatives. We were all pretty proud of this and I’m sure that while my memory (for some reason...) is failing me, we drank a few beers together over this accomplishment.</p>
    <p class="wow fadeIn">Not long after the <a href="http://jsf.co" target="_blank">Jumpstart Foundry</a> program ended, we found another member of our team, Jay Politzer. Jay had spent some time in Washington as a lobbyist before leaving that behind to become a programmer (smart move, Jay). Of course, he was not only a total natural behind a keyboard, but more importantly Jay provided some much needed insight into how money flows through politics and how bills actually go through (or rather, how they don’t go through) the 113th Congress.</p>
    <p class="wow fadeIn">It wasn’t long though before we became painfully aware of how difficult it is create something that is not just educational, but also meaningful, sensible, and unbiased. A consistent goal of the data visualizations we created would be to attempt to display an insight into the political system without intentionally swaying people towards a preconceived answer. Simply put, our primary goal was to avoid the very same bias that we felt the media had.</p>
    <p class="wow fadeIn">We also realized that designing data visualizations is really damn hard. Personally I can remember every single time we debated whether or not to use the color “green” for money, “red” for Republican, or “blue” for Democrat. Obvious concerns were that this would eliminate the use of those colors for any other purpose, which can be very limiting as a designer to have everything look yellow (the contrast == no bueno). Yikes! Likewise, when you’re talking about the visualizations themselves you have to ensure that you’re using the right graph in the right context. Pie charts (apart from having their <a href="http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00018S" target="_blank">long list of enemies</a>) can be very useful when displaying information that all adds up to 100%. For obvious reason they are perhaps not such a good choice when showing the dollar amount a politician earned from a particular PAC when compared to others. Double yikes!</p>
    <p class="wow fadeIn">At last, we all found some semblance of common ground on our prized visualizations and decided to put them out to the Internet to see what the public would think. The feedback of the public was helpful, and yet again we probably had a few more beers to celebrate the occasion. While we still had a ton of work to do, we were humbled by how many people thanked us for what we were attempting, people from both sides of the aisle. Overall, it was a noble attempt and we felt very proud of our hard work, but then there was the whole money issue...</p>
    <h3 class="wow fadeIn">Dolla Dolla Bill, Ya’ll</h3>
    <p class="wow fadeIn">Every business, for-profit or non-profit, requires some form of cash flow to keep the lights on. My professors in college would constantly remind me that a for-profit business that didn’t make money wasn’t a business. <em>It was a hobby</em>. Said another way, there’s a clear difference between a “non-profit” and a “no-profit”. For us, there was certainly an assumption that while we were a for-profit business on the books, we operated more like a non-profit organization would act. The truth is that we wanted to focus on making a great product and not on turning Poliana into a business, which is something it truly never needed to be.</p>
    <p class="wow fadeIn">Our mixed incentives also brought about conflict on a more visionary level. On the one hand, we wanted to make an impact on the political system and on the way Americans view their government. We saw a clear need for this, and we weren’t aware of any other kinds of tool that existed like it. On the other hand, we were in an incubator designed to nurture young, high-growth companies that go on to make lots of money for their shareholders. The irony of being coached to build a profitable company whose mission it was to solve “money in politics” was not lost on us. To quote Abraham Maslow, “I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail.” Many times we found ourselves confused on what was more important: creating a helpful resource for the American public or making money (potentially at the cost of our own ethical standards as you’ll soon read).</p>
    <p class="wow fadeIn">The sad truth is that it’s very hard to make money on something that deserves to be free. Freedom of information is a core tenet of our democracy and something that shouldn’t be monetized. People shouldn’t have to fight for a transparent government: it should be innate to its existence. We believe it’s the responsibility of the media to hold our government accountable and to do so with honesty and integrity (and a spine). Even though we felt the vast majority of major media outlets didn’t do that responsibly, it simply was not worth gaming to our financial advantage, even if we were just making enough to keep the lights on (or the lights of the servers somewhere in Virginia “on”). We just kept asking ourselves: “how in the hell could we ever justify charging for something like this?”</p>
    <p class="wow fadeIn">With that said, we realized those lights weren’t just going to blink by themselves and so we threw around various revenue models. Here’s a shortened list of a few we tried:</p>
    <h5 class="wow fadeIn">Creating a data visualization tool using our dataset for sale to schools and universities (like a <a href="http://en.wikipedia.org/wiki/Bloomberg_Terminal" target="_blank">Bloomberg terminal</a> for political science students).</h5>
    <p class="wow fadeIn">This idea didn’t work because of how difficult it was to break into the pocketbook of a university. The market for educational software is understandably small and has a high barrier to entry primarily based on having deep connections to school administrators (which we didn’t have).</p>
    <h5 class="wow fadeIn">Creating a paid access terminal that allowed you to create your own data visualizations.</h5>
    <p class="wow fadeIn">In short, Poliana would allow everyone to see the graphs that we made for the public, but to make your own using our dataset you’d have to pay via a SaaS model. This was roughly the same the as “Bloomberg terminal” idea, but more open to an undefined (ambiguous) market. It failed, quite simply, because there was no demand for something like this.</p>
    <h5 class="wow fadeIn">Selling data visualizations and information to the media.</h5>
    <p class="wow fadeIn">This was probably our biggest opportunity, but there was disappointment around the corner. Media groups range in scale and audience. For sake of discussion, they can usually be subdivided by “small” (or local), “medium” (or state), or “large” (or national/international). The local news media had very little interest in what we had to offer because of our focus on the national scale (the data is less sparse and easier to aggregate for national politics than otherwise) and therefore it wasn’t relevant to their audience. The statewide media were interested because it would become a key differentiator in their newspaper or online presence. It would also ideally bring trust and credibility to their organization by promoting them as more “data-centric”, but most didn’t have the budget for these kinds of services. The last was the national and international media outlets, which simply were not interested because they all have their own data science teams that they can focus on specific tasks. Why pay a bunch of college students to make data visualizations for your organization when you have a staff of full-time statisticians?</p>
    <h5 class="wow fadeIn">Selling data visualizations and information to lobbyists and politicians.</h5>
    <p class="wow fadeIn">This was a profit model that we never ended up trying but was suggested to us many times. Simply put, we found this revenue model to be really compromising of our ethics and of the core reasons we were creating the site in the first place, so we quickly abandoned the concept.</p>
    <h3 class="wow fadeIn">We Learned a Thing or Eight...</h3>
    <p class="wow fadeIn">We stood between the impasse of using our skills for something good and also trying to make an honest buck. For some it works out, for us it didn’t, and sometimes that’s the way it goes. Even still, we learned some really valuable lessons, so here are a few.</p>
    <ol class="wow fadeIn" start="0">
      <li>If you’re going to be a for-profit company, make sure you can make a profit first. “Experts” have told us this is crucial, but we were slightly defiant to this whack-job ideology.</li>
      <li>Don’t try to make money on ways that compromise who you are and what you stand for. It’s always tempting to make a quick dollar doing something if you promise to “pay it forward” in the future. Our lesson was that you shouldn’t make data visualizations for lobbyists and politicians so they can keep their <a href="https://www.opensecrets.org/bigpicture/reelect.php" target="_blank">90% incumbency rate</a>.</li>
      <li>Don’t start a company around politics unless you’re prepared to be a non-profit. I mean, go ahead and try, but kiss your 401k goodbye.</li>
      <li>In whatever you do, strive for perfection but don’t set your expectations as such. If you won’t release a product until it’s perfect then you shouldn’t release a product at all. People are surprisingly forgiving. If we had released the same borked data visualizations we initially came up with, who knows how much time we could have saved by garnering that feedback. I believe that “trial by fire” is always better than trying to release your magnum opus.</li>
      <li>Do less talking and do more listening. Who knows? If we had listened to people sooner, perhaps you wouldn’t be reading this letter. Entrepreneurs, especially those like ourselves that are new to the game, develop blinders when we talk about our ideas. Take off the beer goggles and listen to people, they know you better than you know yourself sometimes.</li>
      <li>If you have a rare talent or ability, then strive to do something good. If you’ve been fortunate in life, then pass on the good fortune to others. Make the world a better place and try to avoid selling drugs (I hear they’re bad for your kidneys). There’s truly nothing more rewarding than working on a project that helps others. If you have that ability, then why wouldn’t you?</li>
      <li>Take something boring and confusing (politics for instance) and make it fun and accessible. One of the mantras we would repeat to ourselves in the mirror every morning when we brushed our teeth was “bring politics back to the people”. It’s this (albeit naïve) desire to make something that traditionally scares and confuses a person into something that is digestible to them that kept us focused.</li>
      <li>Admit when you’re wrong. Try and keep a level head and remember that the reasons you think your ideas are great is because they’re yours, not because they’re inherently awesome. Although, if both happen to be true: +1.</li>
    </ol>
    <h3 class="wow fadeIn">A Few Thank You Cards</h3>
    <p class="wow fadeIn">While Poliana took a nosedive, there’s a ton of great folks out there who are somehow able to keep the lights on. It’s time for an obligatory (but well-deserved) shout out to all the awesome people that helped us along the way. Here are a few really awesome groups of people that are doing cool things in the political space.</p>
    <h5 class="wow fadeIn">Maplight</h5>
    <p class="wow fadeIn">We had a few meetings with these <a href="http://maplight.org/" target="_blank">genuine and crazy intelligent guys</a>. Our goals were similar to theirs in that we wanted to make the political system simpler for the general public, and they do a terrific job.</p>
    <h5 class="wow fadeIn">Sunlight Foundation</h5>
    <p class="wow fadeIn"><a href="http://sunlightfoundation.com/" target="_blank">These guys</a> were really generous in lending us their data and we viewed them somewhat as mentors throughout the whole process. These people work tirelessly to aggregate the American government’s political data and they do it better than anyone we know.</p>
    <h5 class="wow fadeIn">Center for Responsive Politics</h5>
    <p class="wow fadeIn">We had a similar connection to <a href="https://www.opensecrets.org/" target="_blank">the Center for Reponsive Politics</a> as with Sunlight. We sought the help of the magnificent Sheila Krumholz (who does some rather inspiring work might we add) and her advice and support was always incredibly valuable.</p>
    <h5 class="wow fadeIn">Govtrack</h5>
    <p class="wow fadeIn"><a href="https://www.govtrack.us/" target="_blank">This site</a> is run by Joshua Tauberer, who we somewhat worshipped like a golden calf. I don’t remember if we ever met or talked to Josh, but he’s probably the smartest guy on the entire Internet. Thanks Josh for allowing us to steal some of your algorithms and pretty much all of your data.</p>
    <p class="wow fadeIn">Likewise we had a pretty great set of mentors that we’d like to thank for their support and advice on the journey are (in no particular order): Sal Novin, Alan Huffman, Tod Fetherling, Ben Stucki, Will Limratana, Dave Delaney, Matt Mueller, Chris Sloan, Michael Burcham, David Ledgerwood, Marcus Whitney, Vic Gatto, Rich Lockwood, James Pierce, Dan Johnson, Dr. Jeff Cornwall, Dr. Mark Schenkel, Jose Gonzalez, Teja Yenamandra, JohnPaul Bennett, Mike Herman, Lauren Rogala, Bryan Rogala, Rachel Moore, Frashier Baudry, all the cool companies in <a href="http://jsf.co" target="_blank">Jumpstart</a> and all the great staff, and everyone else at the <a href="http://www.ec.co/" target="_blank">Nashville Entrepreneur Center</a>.</p>
    <p class="wow fadeIn">We’re truly indebted to each of you, thanks for your tireless work, and there’s a beer with your name on it whenever you call.</p>
    <h3 class="wow fadeIn">Where You At?</h3>
    <p class="wow fadeIn">Enough with the thank you letters. Here’s where we’re each at individually and where this leaves the experiment that is Poliana.</p>
    <h5 class="wow fadeIn">Seth Whiting</h5>
    <p class="wow fadeIn">Seth is still entrepreneurial but has taken an interest in programming and now works as a developer around Nashville where he makes the Internet a better place one pixel at a time.</p>
    <h5 class="wow fadeIn">Shawn Whiting</h5>
    <p class="wow fadeIn">Shawn has started a virtual reality company based around making games and online worlds through which people can traverse. It sounds super interesting and way above my knowledge threshold, but you can <a href="http://convrge.co/" target="_blank">learn more about them here</a>.</p>
    <h5 class="wow fadeIn">Kenny House</h5>
    <p class="wow fadeIn">Kenny is a rockstar software developer at another Nashville startup, <a href="http://www.octovis.com/" target="_blank">Octovis</a>. He spends his time messing with the bitrate and audio quality of Bluetooth stethoscopes and making Android development not suck so much.</p>
    <h5 class="wow fadeIn">Grayson Carroll</h5>
    <p class="wow fadeIn">Grayson is a web developer around Nashville and has recently begun working full-time at <a href="http://datafi.com/" target="_blank">DataFi</a>, which basically is sick company that makes predictive real estate and analytics software.</p>
    <h5 class="wow fadeIn">Patrick Cason</h5>
    <p class="wow fadeIn">Patrick (yours truly) is the Lead Front-End Engineer and Designer for <a href="http://www.octovis.com/" target="_blank">Octovis</a>. He makes web applications and Android applications that make the lives of doctors, nurses, and surgeons easier and more intuitive.</p>
    <h5 class="wow fadeIn">David Gilmore</h5>
    <p class="wow fadeIn">David works as a developer at <a href="http://www.digitalreasoning.com/" target="_blank">Digital Reasoning</a>, a data science and natural language processing software company just outside of Nashville. He spends his time being secretive about his work, all the while spinning up 500-node EC2 clusters like a well-trained ninja jumping in for a quick snap of someone’s neck.</p>
    <h5 class="wow fadeIn">Jay Politzer</h5>
    <p class="wow fadeIn">Jay works as the Director of Engineering at <a href="http://www.octovis.com/" target="_blank">Octovis</a> (with Patrick and Kenny) and spends a lot of his time merging the gap between nerdy developers and business goals. He too is a rockstar and spends the majority of his time working with WebRTC and Node.js (like a boss).</p>
    <h3 class="wow fadeIn">Closing Time</h3>
    <p class="wow fadeIn">So Poliana might be shutting down, but we’re not letting all of our hard work go to waste! To celebrate, we’re <a href="https://github.com/polianainc" target="_blank">open-sourcing every line of code</a> (you should read our Git commit messages, there are some gems in there somewhere), <a href="https://s3.amazonaws.com/poliana-designs/poliana-designs.zip" target="_blank">as well as all of our designs</a>. Note that we may not still have every version of the designs, but we’ll put up all that we can find. We hope that in some way our work will inspire others to create cool stuff too. Please feel free to use any and all of our work on your projects; it would be an honor!</p>
    <p class="wow fadeIn">We’re all certainly very sad to let go of this project, but it would be incredible if someone else picked up where we left off. Each member of this team is deeply passionate about political reform and improving our government for the better. In a round about sense, it’s also made us each a little bit more patriotic as well. And let’s be honest, perhaps someday one of us will pick up the torch again and try to recreate Poliana, but no promises! So go forth, break things, and try to have fun while you’re at it. Life is too short to waste your time doing things that don’t kick ass.</p>
    <p class="right">Peace, love, and rock and roll,<br><i>The Poliana Team</i></p>
    <p class="center small wow fadeIn">If you feel some strong urge to talk to us still, you can do so at <a href="mailto:polianaproject@gmail.com">polianaproject@gmail.com</a>.</p>
    <div class="wow fadeIn" id="disqus_thread"></div>
    <script type="text/javascript">
      var disqus_shortname = 'polianainc';

      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    </script>
    <noscript class="wow fadeIn">Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" target="_blank">comments powered by Disqus.</a></noscript>
    <img src="images/logo-mark.png" id="footer-logo" alt="Poliana" class="wow fadeIn">
  </div>
  <script src="bower_components/wowjs/dist/wow.min.js"></script>
  <script src="js/min/app-min.js"></script>
</body>
</html>
